pipeline {
    agent any

    stages {
        stage('Terraform Apply') {
            steps {
                build job: 'terraform-apply'
            }
        }
    }

    post {
        always {
            script {
                // Ensures cleanup and execution of dependent destroy operations
                build job: 'terraform-destroy'
                cleanWs()
            }
        }
    }
}
