name: Continuous Deployment

on:
  push:
    branches: ['master', 'main']

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-west-1.amazonaws.com
  TF_VAR_postgres_db: ${{ secrets.POSTGRES_DB }}
  TF_VAR_postgres_user: ${{ secrets.POSTGRES_USER }}
  TF_VAR_postgres_password: ${{ secrets.POSTGRES_PASSWORD }}
  TF_VAR_postgres_host: ${{ secrets.POSTGRES_HOST }}

jobs:
  terraform_apply:
    name: Terraform Apply
    uses: ./.github/workflows/terraform_apply.yml
    secrets: inherit

  aws_deploy:
    name: AWS Deploy
    needs: terraform_apply
    uses: ./.github/workflows/aws_deploy.yml
    secrets: inherit

  terraform_destroy:
    name: Terraform Destroy
    needs: aws_deploy
    uses: ./.github/workflows/terraform_destroy.yml
    secrets: inherit
