name: Continuous Deployment

on:
  push:
    branches: ["master", "main"]

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-west-1.amazonaws.com
  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}

jobs:
  terraform_apply:
    name: Terraform Apply
    uses: ./.github/workflows/terraform_gcp_apply.yml
    secrets: inherit

  gcp_deploy:
    name: GCP Deploy
    needs: terraform_apply
    uses: ./.github/workflows/gcp_deploy.yml
    secrets: inherit

  terraform_destroy:
    name: Terraform Destroy
    needs: gcp_deploy
    if: ${{ always() }}
    uses: ./.github/workflows/terraform_gcp_destroy.yml
    secrets: inherit
