name: Trigger Jenkins Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins Job
        env:
          JENKINS_URL: ${{ secrets.JENKINS_URL }}
          JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
        run: |
          response=$(curl -s -w "%{http_code}" "${JENKINS_URL}/buildWithParameters?token=${JENKINS_TOKEN}")
          if [[ $response == *"201"* ]] || [[ $response == *"200"* ]]; then
            echo "Successfully triggered Jenkins pipeline"
          else
            echo "Failed to trigger Jenkins pipeline"
            exit 1
          fi
