name: Jenkins Pipeline Integration

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins Job
        id: trigger
        run: |
          # Trigger the job with token and get the queue location
          QUEUE_URL=$(curl -s -X POST \
            "${{ secrets.JENKINS_URL }}/job/ecc-project/buildWithParameters?token=${{ secrets.JENKINS_TOKEN }}&cause=Triggered+from+GitHub+PR+${{ github.event.pull_request.number }}&PR_NUMBER=${{ github.event.pull_request.number }}&GITHUB_SHA=${{ github.sha }}" \
            -D - | grep -i "location:" | cut -d " " -f 2- | tr -d '\r')

          echo "Queue URL: $QUEUE_URL"
          echo "queue_url=$QUEUE_URL" >> $GITHUB_OUTPUT

      - name: Get Build ID
        id: build
        run: |
          # Function to extract build number from queue item
          get_build_number() {
            curl -s "$1api/json" | jq -r '.executable.number // empty'
          }

          # Poll until we get a build number
          QUEUE_URL="${{ steps.trigger.outputs.queue_url }}"
          BUILD_NUMBER=""
          for i in {1..30}; do
            BUILD_NUMBER=$(get_build_number "$QUEUE_URL")
            if [ ! -z "$BUILD_NUMBER" ]; then
              echo "build_number=$BUILD_NUMBER" >> $GITHUB_OUTPUT
              break
            fi
            echo "Waiting for build to start... (attempt $i/30)"
            sleep 10
          done

          if [ -z "$BUILD_NUMBER" ]; then
            echo "Failed to get build number after 5 minutes"
            exit 1
          fi

      - name: Wait for Build Completion
        run: |
          # Function to check build status
          get_build_status() {
            curl -s "${{ secrets.JENKINS_URL }}/job/ecc-project/${{ steps.build.outputs.build_number }}/api/json" | \
              jq -r '.result'
          }

          # Poll until build completes
          for i in {1..60}; do
            STATUS=$(get_build_status)
            echo "Current status: $STATUS"

            if [ "$STATUS" = "SUCCESS" ]; then
              echo "Build succeeded!"
              exit 0
            elif [ "$STATUS" = "FAILURE" ] || [ "$STATUS" = "ABORTED" ]; then
              echo "Build failed or was aborted"
              exit 1
            elif [ "$STATUS" = "null" ]; then
              echo "Build still in progress... (check $i/60)"
              sleep 30
              continue
            else
              echo "Unexpected status: $STATUS"
              exit 1
            fi
          done

          echo "Build timed out after 30 minutes"
          exit 1
