name: "Terraform Destroy Google Cloud Platform"

on:
  workflow_call:

env:
  TF_VAR_postgres_db: ${{ secrets.POSTGRES_DB }}
  TF_VAR_postgres_user: ${{ secrets.POSTGRES_USER }}
  TF_VAR_postgres_password: ${{ secrets.POSTGRES_PASSWORD }}
  TF_VAR_postgres_host: ${{ secrets.POSTGRES_HOST }}

jobs:
  terraform:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/gcp
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure GCP Credentials
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: ">= 502.0.0"
          project_id: "${{ secrets.GCP_PROJECT_ID }}"

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.7
          terraform_wrapper: false

      - name: Terraform Format
        id: fmt
        working-directory: terraform/gcp
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        working-directory: terraform/gcp
        run: terraform init

      - name: Terraform Plan Destroy
        id: plan
        working-directory: terraform/gcp
        run: terraform plan -destroy -no-color

      - name: Terraform Destroy
        working-directory: terraform/gcp
        run: terraform destroy -auto-approve
